# Generated by Django 5.1.4 on 2024-12-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_value', models.CharField(max_length=255)),
                ('max_padroes', models.IntegerField()),
                ('informacao', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('imagem', models.BinaryField()),
            ],
        ),
    ]
