# Generated by Django 5.1.2 on 2025-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='qr_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
