# Generated by Django 5.1.2 on 2025-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evento_qr_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='id_entrada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
